### ISSUE TITLE
Does this work with Python 3.  I have a pip error

### ISSUE THREAD

**Issue by robdempsey** [svenkreiss/pysparkling#2]
Hi

python --version
Python 3.4.3 :: Anaconda 2.2.0 (64-bit)

pip install pysparkling
Collecting pysparkling
  Using cached pysparkling-0.2.16.tar.gz
Collecting boto>=2.38.0 (from pysparkling)
  Using cached boto-2.38.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): requests>=2.7.0 in /root/anaconda3/lib/python3.4/site-packages (from pysparkling)
Installing collected packages: boto, pysparkling
  Found existing installation: boto 2.36.0
    DEPRECATION: Uninstalling a distutils installed project (boto) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling boto-2.36.0:
      Successfully uninstalled boto-2.36.0
  Rolling back uninstall of boto
Exception:
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.4/site-packages/pip/basecommand.py", line 223, in main
    status = self.run(options, args)
  File "/root/anaconda3/lib/python3.4/site-packages/pip/commands/install.py", line 297, in run
    root=options.root_path,
  File "/root/anaconda3/lib/python3.4/site-packages/pip/req/req_set.py", line 622, in install
    **kwargs
  File "/root/anaconda3/lib/python3.4/site-packages/pip/req/req_install.py", line 808, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/root/anaconda3/lib/python3.4/site-packages/pip/req/req_install.py", line 1003, in move_wheel_files
    isolated=self.isolated,
  File "/root/anaconda3/lib/python3.4/site-packages/pip/wheel.py", line 338, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/root/anaconda3/lib/python3.4/site-packages/pip/wheel.py", line 322, in clobber
    os.utime(destfile, (st.st_atime, st.st_mtime))
PermissionError: [Errno 1] Operation not permitted

Any ideas

Rob

**Comment by svenkreiss** [comment]
Strange. Python 3.4 is part of the standard tests that are always run.

However, that test is not using Anaconda. Anaconda seems to be a little behind on the versions of boto and requests. I have lowered the version requirements so that it is compatible with what Anaconda ships with now.

Can you try to upgrade with `pip install --upgrade pysparkling` and see whether that helped?

**Comment by robdempsey** [comment]
That did the trick.  Thanks
