### ISSUE TITLE
reduceByKey() and groupByKey() throw errors with numpy arrays

### ISSUE THREAD

**Issue by pganssle** [svenkreiss/pysparkling#35]
Because `groupByKey()` uses `sorted()` with no key function, whenever keys are repeated (the only reason you'd want to reduce or group by keys anyway) and the comparators of numpy arrays are not well-defined, when an RDD has numpy arrays as *values*, a `ValueError` is thrown:

```python
import numpy as np
from operator import add
from pysparkling import Context as SparkContext

sc = SparkContext()

keys = (0, 0, 1, 1, 2, 2)
values = (np.ones((2, 3)) * (i + k) for i, k in enumerate(keys))

rdd = sc.parallelize(zip(keys, values))
a = rdd.reduceByKey(add).collect()

print(a)
```

Result (Anaconda Python 3.5 on Linux):
```
$ python3.5 np_reduce_by_key.py
Traceback (most recent call last):
  File "np_reduce_by_key.py", line 13, in <module>
    a = rdd.reduceByKey(add).collect()
  File "~/anaconda3/lib/python3.5/site-packages/pysparkling/rdd.py", line 1144, in reduceByKey
    return self.groupByKey().mapValues(lambda x: functools.reduce(f, x))
  File "~/anaconda3/lib/python3.5/site-packages/pysparkling/rdd.py", line 695, in groupByKey
    sorted(self.collect()),
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

On a pySpark instance, the result is (adjusted spacing):
```
[(0, array([[ 1.,  1.,  1.], [ 1.,  1.,  1.]])),
 (2, array([[13., 13., 13.], [13., 13., 13.]])),
 (1, array([[ 7.,  7.,  7.], [ 7.,  7.,  7.]]))]
```

Ideally, this operation wouldn't involve sorting at all, but I understand why it's done that way. I think the proper mitigation is to use:

``` python
from operator import itemgetter
def groupby(*args, **kwargs):
    ...
    sorted(self.collect(), key=itemgetter(0)),
    ...
```

**Comment by pganssle** [comment]
PR forthcoming.

**Comment by svenkreiss** [comment]
Looking forward to it :+1:
